version: '3.7'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - bd-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: password
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database

  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   volumes:
  #     - pgadmin:/var/lib/pgadmin
  #   ports:
  #     - 5050:80
  #   depends_on:
  #     - postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 1234:8080
    depends_on:
      - postgres

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - bd-mongo:/data/db
      - ./tmp:/resources
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: database

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
    depends_on:
      - mongo

volumes:
  bd-postgres:
  bd-mongo:
  # pgadmin:
