version: '3.7'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: app
    restart: on-failure
    ports:
      - $SERVER_HOST_PORT:8000
    depends_on:
      - mongodb
      - postgres
    environment:
      SERVER_PORT: 8000
      SPRING_PROFILES_ACTIVE: prod
      # MongoDB
      SPRING_DATA_MONGODB_HOST: mongodb_host
      SPRING_DATA_MONGODB_USERNAME: $MONGO_USER
      SPRING_DATA_MONGODB_PASSWORD: $MONGO_PASSWORD
      SPRING_DATA_MONGODB_DATABASE: $MONGO_DB
      SPRING_DATA_MONGODB_PORT: 27017
      # Postgres
      POSTGRES_HOST: postgres_host
      POSTGRES_DATABASE: $POSTGRES_DB
      SPRING_DATASOURCE_USERNAME: $POSTGRES_USER
      SPRING_DATASOURCE_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_PORT: 5432
    networks:
      - main-network

  mongodb:
    image: mongo:5.0.8
    hostname: mongodb_host
    ports:
      - $MONGO_HOST_PORT:27017
    restart: unless-stopped
    volumes:
      - bd-mongo:/data/db
      - ./initialization/mongo/init:/docker-entrypoint-initdb.d/
      - ./initialization/mongo/resources:/resources/init/
      - ./initialization/csv:/resources/csv/
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_DB
      NAME_CSV_FILE: $NAME_CSV_FILE
    networks:
      - main-network

  postgres:
    image: postgres:14-alpine
    hostname: postgres_host
    ports:
      - $POSTGRES_HOST_PORT:5432
    restart: unless-stopped
    volumes:
      - bd-postgres:/var/lib/postgresql/data
      - ./initialization/postgres/init:/docker-entrypoint-initdb.d/
      - ./initialization/postgres/resources:/resources/init/
      - ./initialization/csv:/resources/csv/
    environment:
      POSTGRES_HOST_AUTH_METHOD: password
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      NAME_CSV_FILE: $NAME_CSV_FILE
    networks:
      - main-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.1
    restart: always
    ports:
      - $ELASTIC_HOST_PORT:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - bd-elastic:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - xpack.security.enabled=false
    networks:
      - main-network

  logstash:
    image: docker.elastic.co/logstash/logstash:8.4.1
    restart: always
    ports:
      - $LOGSTASH_HOST_PORT:5000
    volumes:
      - ./initialization/logstash/pipeline:/usr/share/logstash/pipeline/
      - ./initialization/csv:/resources/csv/
    environment:
      - NAME_CSV_FILE=$NAME_CSV_FILE
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - 'LS_JAVA_OPTS=-Xmx256m -Xms256m'
      - pipeline.workers=1
    networks:
      - main-network
    depends_on:
      - elasticsearch
    links:
      - elasticsearch

volumes:
  bd-postgres:
  bd-mongo:
  bd-elastic:

networks:
  main-network:
