version: '3.7'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: app
    restart: on-failure
    ports:
      - '8081:8081'
    depends_on:
      - mongodb
      - postgres
    environment:
      SERVER_PORT: 8081
      SPRING_PROFILES_ACTIVE: prod
      # MongoDB
      SPRING_DATA_MONGODB_HOST: mongodb_host
      SPRING_DATA_MONGODB_USERNAME: root
      SPRING_DATA_MONGODB_PASSWORD: password
      SPRING_DATA_MONGODB_PORT: 27017
      # Postgres
      POSTGRES_HOST: postgres_host
      POSTGRES_DATABASE: database
      POSTGRES_PORT: 5432
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - main-network

  mongodb:
    image: mongo:5.0.8
    hostname: mongodb_host
    ports:
      - '27017:27017'
    restart: unless-stopped
    volumes:
      - bd-mongo:/data/db
      - ./initialization/mongo/init:/docker-entrypoint-initdb.d/
      - ./initialization/mongo/resources:/resources/init/
      - ./initialization/csv:/resources/csv/
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: database
    networks:
      - main-network

  postgres:
    image: postgres:14-alpine
    hostname: postgres_host
    ports:
      - '5432:5432'
    restart: unless-stopped
    volumes:
      - bd-postgres:/var/lib/postgresql/data
      - ./initialization/postgres/init:/docker-entrypoint-initdb.d/
      - ./initialization/postgres/resources:/resources/init/
      - ./initialization/csv:/resources/csv/
    environment:
      POSTGRES_HOST_AUTH_METHOD: password
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    networks:
      - main-network

volumes:
  bd-postgres:
  bd-mongo:

networks:
  main-network:
