###
// Retorna lista de accidentes ocurridos entre las fechas start y end.
// Las fechas deben seguir el formato YYYY-MM-DD.
GET http://localhost:8080/accidents/between-dates?start=2016-02-08&end=2016-02-09 HTTP/1.1

###
// Retorna lista de accidentes ocurridos a una distancia (radius) en km de un punto geográfico
// dado por las coordenadas longitude y latitude.
GET http://localhost:8080/accidents/near?longitude=-84.058723&latitude=39.865147&radius=10 HTTP/1.1

###
// Retorna la distancia promedio (en metros) desde el inicio al fin del accidente
GET http://localhost:8080/accidents/average-distance HTTP/1.1

###
// Retorna las 5 calles con más accidentes
GET http://localhost:8080/accidents/dangerous-streets HTTP/1.1

###
// Retorna la distancia promedio (en km) de cada accidente a los 10 más cercanos
GET http://localhost:8080/accidents/near/average-distance?page=1&perPage=10 HTTP/1.1

###
// Retorna las condiciones más comunes en los accidentes
GET http://localhost:8080/accidents/getCommonConditions HTTP/1.1

###
// Retorna los puntos más peligrosos a partir de un determinado radio
GET http://localhost:8080/accidents/getMostDangerousPoints?radius=2 HTTP/1.1