-- DROP TABLE
DROP TABLE IF EXISTS public.accident;
-- CREATE TABLE ACCIDENT
CREATE TABLE accident (
  id varchar(50) NULL,
  "source" varchar(50) NULL,
  tmc varchar(15) NULL,
  severity int4 NULL,
  start_time timestamp NULL,
  end_time timestamp NULL,
  start_lat float4 NULL,
  start_lng float4 NULL,
  end_lat float4 NULL,
  end_lng float4 NULL,
  distance float4 NULL,
  description varchar(400) NULL,
  "number" float4 NULL,
  street varchar(50) NULL,
  side varchar(50) NULL,
  city varchar(50) NULL,
  county varchar(50) NULL,
  state varchar(50) NULL,
  zipcode varchar(50) NULL,
  country varchar(50) NULL,
  timezone varchar(50) NULL,
  airport_code varchar(50) NULL,
  weather_timestamp timestamp NULL,
  temperature float4 NULL,
  wind_chill float4 NULL,
  humidity float4 NULL,
  pressure float4 NULL,
  visibility float4 NULL,
  wind_direction varchar(50) NULL,
  wind_speed float4 NULL,
  precipitation float4 NULL,
  weather_condition varchar(50) NULL,
  amenity bool NULL,
  bump bool NULL,
  crossing bool NULL,
  give_way bool NULL,
  junction bool NULL,
  no_exit bool NULL,
  railway bool NULL,
  roundabout bool NULL,
  station bool NULL,
  stop bool NULL,
  traffic_calming bool NULL,
  traffic_signal bool NULL,
  turning_loop bool NULL,
  sunrise_sunset varchar(50) NULL,
  civil_twilight varchar(50) NULL,
  nautical_twilight varchar(50) NULL,
  astronomical_twilight varchar(50) NULL
);
-- IMPORT DATA FROM CSV
COPY accident
FROM '/resources/tmp/US_Accidents_Dec19_short-199.csv' DELIMITER ',' CSV HEADER;